name: airnav_helpdesk
description: "Helpdesk App Built by AirNav Indonesia"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Backend & Firebase services
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4

  # Code generation support
  envied: ^1.3.1
  json_annotation: ^4.9.0

  # Core utilities
  collection: ^1.19.1
  equatable: ^2.0.5
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2

  # Internationalization
  intl: ^0.20.2

  # Local data persistence
  flutter_secure_storage: ^9.2.4
  get_storage: ^2.1.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2

  # State management & navigation
  get: ^4.7.2
  persistent_bottom_nav_bar: ^6.2.1

  # UI components & assets
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  easy_stepper: ^0.9.1
  fl_chart: ^1.1.1
  flutter_svg: ^2.2.2
  font_awesome_flutter: ^10.12.0
  google_fonts: ^6.3.2
  image_picker: ^1.2.1
  infinite_scroll_pagination: ^5.1.1
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.10.3
  envied_generator: ^1.3.1
  json_serializable: ^6.8.0

  # Linting
  flutter_lints: ^5.0.0

  # Logging
  logger: ^2.6.2

  # Testing
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true